spring.application.name=wallet-api

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/wallet_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2
spring.datasource.username=2BdaPF5Q1mjae7o.root
spring.datasource.password=cwxdqZWDrr0T5Rqr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect